set -g default-terminal "tmux-256color"
run-shell 'if test -x ~/.nix-profile/bin/zsh; then tmux set -g default-shell ~/.nix-profile/bin/zsh; else tmux set -g default-shell /opt/homebrew/bin/zsh; fi'

set -g mouse on
set -ga terminal-overrides ",xterm-256color:Tc"
setw -g mode-keys vi

# prefixをCtrl+q に変更
set -g prefix C-q
unbind-key C-b
bind-key C-q send-prefix

set -g status on
set -g status-left-length 60
set -g status-right-length 120
set -g status-justify centre
set -g status-position bottom

setw -g window-status-current-style fg=white,none

set -g status-left ' C-q:prefix  -:hsplit  |:vsplit  r:reload  ,:claude'

set -g status-right ''

# active な pane がいるディレクトリを表示
set -g window-status-current-format '#[fg=colour255,bg=colour241]'

set -g pane-active-border-style fg=black,bg=colour231

set -g status-bg "#455A64"
set -g status-fg "#ECEFF1"

# prefix + r 設定再読み込み
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# prefix + | でアクティブなペインを縦に分割する
bind-key | split-window -hc "#{pane_current_path}"

# prefix + - でアクティブなペインを横に分割する
bind-key - split-window -vc "#{pane_current_path}"

bind , run-shell 'zsh -ic "_tmuxpopup-claude"'

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe "pbcopy"

set -s escape-time 0
