tap "leoafarias/fvm"
brew "bat"
brew "fontconfig"
brew "glib"
brew "bundletool"
brew "cmake"
brew "cocoapods"
brew "coreutils"
brew "curl"
brew "direnv"
brew "emacs"
brew "fd"
brew "libsodium"
brew "ffmpeg"
brew "fish"
brew "fontforge"
brew "fzf"
brew "gh"
brew "ghq"
brew "gifsicle"
brew "git"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "gradle"
brew "grep"
brew "hub"
brew "hugo"
brew "imagemagick"
brew "jq"
brew "kotlin"
brew "kubernetes-cli"
brew "lcov"
brew "less"
brew "lsd"
brew "lua"
brew "mas"
brew "neovim"
brew "nkf"
brew "pkgconf"
brew "node-build"
brew "nodenv"
brew "pidcat"
brew "pinact"
brew "pinentry-mac"
brew "pngquant"
brew "postgresql@14"
brew "potrace"
brew "ruby-build"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rustup"
brew "source-highlight"
brew "the_platinum_searcher"
brew "tidy-html5"
brew "tig"
brew "tmux"
brew "tree"
brew "universal-ctags"
brew "vim"
brew "yq"
brew "leoafarias/fvm/fvm"
cask "flutter"
cask "font-cica"
cask "gcloud-cli"
cask "swiftformat-for-xcode"
cask "temurin@17"
cask "xquartz"
mas "Amphetamine", id: 937984704
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
