gui:
  language: 'en'
  nerdFontsVersion: '3'
  authorColors:
    '*': '#BDBDBD'
  commitAuthorShortLength: 0
  commitAuthorLongLength: 0

git:
  autoFetch: false # f
  autoRefresh: false # R
  fetchAll: false
  pagers:
    - pager: bat
  mainBranches:
    - main
    - develop
    - master
  branchPrefix: 'feature/'
  branchLogCmd: git log -p --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
  merging:
    args: '-S'

customCommands:
  - key: 'H'
    context: 'status, commits, localBranches'
    command: 'gpr'
    output: terminal
