gui:
  language: 'en'
  nerdFontsVersion: '3'
  authorColors:
    '*': '#BDBDBD'
  commitAuthorShortLength: 0
  commitAuthorLongLength: 0

git:
  autoFetch: false # f
  autoRefresh: false # R
  fetchAll: false
  pagers:
    - pager: bat
  mainBranches:
    - main
    - develop
    - master

customCommands:
  - key: 'H'
    context: 'global, commits'
    command: 'hub mkpr'
