name: Provisioning

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.head_ref || 'develop' }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Provisioning
      run: |
        export HOMEBREW_BUNDLE_MAS_SKIP="$(grep mas <Brewfile | grep -v brew | awk -F '[, "]' '{printf $3" "}')"
        /bin/bash -ex setup.sh
